version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: numerlical_db
    ports:
      - "3307:3306"

  fast-api:
    build: ./numer_db/API
    container_name: fast-api
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: host.docker.internal
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: numerlical_db

  frontend:
      build: ./
      container_name: front-end
      ports:
        - "5174:5174"
      networks:
        - app-network
      depends_on:
        - fast-api
networks:
  app-network:
    driver: bridge
